/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessRouteImport } from './routes/api/process'
import { Route as ApiReportsIndexRouteImport } from './routes/api/reports/index'
import { Route as ApiReportsIdRouteImport } from './routes/api/reports/$id'
import { Route as ApiReportsIdPdfRouteImport } from './routes/api/reports/$id/pdf'

const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessRoute = ApiProcessRouteImport.update({
  id: '/api/process',
  path: '/api/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIndexRoute = ApiReportsIndexRouteImport.update({
  id: '/api/reports/',
  path: '/api/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdRoute = ApiReportsIdRouteImport.update({
  id: '/api/reports/$id',
  path: '/api/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdPdfRoute = ApiReportsIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ApiReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/api/process': typeof ApiProcessRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/reports/': typeof ApiReportsIndexRoute
  '/api/reports/$id/pdf': typeof ApiReportsIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/api/process': typeof ApiProcessRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/reports': typeof ApiReportsIndexRoute
  '/api/reports/$id/pdf': typeof ApiReportsIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/api/process': typeof ApiProcessRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/reports/': typeof ApiReportsIndexRoute
  '/api/reports/$id/pdf': typeof ApiReportsIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/api/process'
    | '/api/reports/$id'
    | '/api/reports/'
    | '/api/reports/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/api/process'
    | '/api/reports/$id'
    | '/api/reports'
    | '/api/reports/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/api/process'
    | '/api/reports/$id'
    | '/api/reports/'
    | '/api/reports/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  ApiProcessRoute: typeof ApiProcessRoute
  ApiReportsIdRoute: typeof ApiReportsIdRouteWithChildren
  ApiReportsIndexRoute: typeof ApiReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process': {
      id: '/api/process'
      path: '/api/process'
      fullPath: '/api/process'
      preLoaderRoute: typeof ApiProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/': {
      id: '/api/reports/'
      path: '/api/reports'
      fullPath: '/api/reports/'
      preLoaderRoute: typeof ApiReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id': {
      id: '/api/reports/$id'
      path: '/api/reports/$id'
      fullPath: '/api/reports/$id'
      preLoaderRoute: typeof ApiReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id/pdf': {
      id: '/api/reports/$id/pdf'
      path: '/pdf'
      fullPath: '/api/reports/$id/pdf'
      preLoaderRoute: typeof ApiReportsIdPdfRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
  }
}

interface ApiReportsIdRouteChildren {
  ApiReportsIdPdfRoute: typeof ApiReportsIdPdfRoute
}

const ApiReportsIdRouteChildren: ApiReportsIdRouteChildren = {
  ApiReportsIdPdfRoute: ApiReportsIdPdfRoute,
}

const ApiReportsIdRouteWithChildren = ApiReportsIdRoute._addFileChildren(
  ApiReportsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  ApiProcessRoute: ApiProcessRoute,
  ApiReportsIdRoute: ApiReportsIdRouteWithChildren,
  ApiReportsIndexRoute: ApiReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
